#!/bin/bash

source scripts/vars.sh

installcleanup() {
    clear
    echo "Cleaning up and cancelling installation..."

    umount -R /mnt 2>/dev/null

    if [[ $platform == "EFI" ]]; then
        swapoff /dev/mapper/archvolume-swap 2>/dev/null
        lvremove -f archvolume/swap 2>/dev/null
        lvremove -f archvolume/root 2>/dev/null
        vgremove -f archvolume 2>/dev/null
        pvremove ${LVM_DEVICE} 2>/dev/null

        if [[ $disk_encrypt == "y" ]]; then
            cryptsetup close cryptlvm 2>/dev/null
        fi
    else
        swapoff ${partition2} 2>/dev/null
    fi

    clear
    echo "========================================="
    echo "     Installation Cancelled"
    echo "========================================="
    echo "Disk has been cleaned up."
    echo "You can safely rerun the script."
    sleep 2
    exit 0
}

set_partition_names() {
    if [[ ${DISK} =~ "nvme" ]]; then
        partition1="${DISK}p1"
        partition2="${DISK}p2"
        partition3="${DISK}p3"
    else
        partition1="${DISK}1"
        partition2="${DISK}2"
        partition3="${DISK}3"
    fi
}


efisetup() {
    set_partition_names

    if [[ $disk_encrypt == "y" ]]; then
        echo "Setting up LUKS encryption..."

        while true; do
            if echo -n "${password}" | cryptsetup -y -v luksFormat ${partition2} -; then
                break
            else
                echo "Encryption setup failed. Retrying..."
                read -p "Press Enter to retry or Ctrl+C to exit..."
            fi
        done

        while true; do
            if echo -n "${password}" | cryptsetup open ${partition2} cryptlvm -; then
                break
            else
                echo "Failed to open encrypted partition. Retrying..."
                read -p "Press Enter to retry or Ctrl+C to exit..."
            fi
        done

        LVM_DEVICE="/dev/mapper/cryptlvm"
    else
        echo "Setting up without encryption..."
        LVM_DEVICE=${partition2}
    fi

    # LVM
    pvcreate $LVM_DEVICE
    vgcreate archvolume $LVM_DEVICE
    lvcreate -L 4G -n swap archvolume
    lvcreate -l 100%FREE -n root archvolume

    # Filesystems
    mkfs.ext4 /dev/mapper/archvolume-root
    mkswap /dev/mapper/archvolume-swap

    # Mount
    mount /dev/mapper/archvolume-root /mnt
    swapon /dev/mapper/archvolume-swap

    # EFI
    mkfs.fat -F32 ${partition1}
    mkdir /mnt/efi
    mount ${partition1} /mnt/efi
}

biossetup() {
    set_partition_names

    # partition1: 2M BIOS boot (no fs, GRUB embed)
    # partition2: 4G swap
    # partition3: root

    mkfs.ext4 ${partition3}
    mkswap ${partition2}

    mount ${partition3} /mnt
    swapon ${partition2}



# Get rid of everything
umount -A --recursive /mnt 2>/dev/null
sgdisk -Z ${DISK}
sgdisk -a 2048 -o ${DISK}

if [[ $platform == "EFI" ]]; then
    # EFI: 3G EFI + rest for LVM
    sgdisk -n 1::+3G --typecode=1:ef00 --change-name=1:'EFIBOOT' ${DISK}
    sgdisk -n 2::-0 --typecode=2:8300 --change-name=2:'ROOT' ${DISK}
    partprobe ${DISK}
    efisetup

elif [[ $platform == "BIOS" ]]; then
    # BIOS: 2M BIOS boot + 4G swap + rest root
    sgdisk -n 1::+2M --typecode=1:ef02 --change-name=1:'BIOSBOOT' ${DISK}
    sgdisk -n 2::+4G --typecode=2:8200 --change-name=2:'SWAP' ${DISK}
    sgdisk -n 3::-0 --typecode=3:8300 --change-name=3:'ROOT' ${DISK}
    sgdisk -A 1:set:2 ${DISK}
    partprobe ${DISK}
    biossetup

else
    echo "ERROR: Unknown platform, exiting..."
    exit 1
fi

# Confirmation
while true; do
    lsblk
    read -p "Continue (y/n): " answer
    if [[ $answer == "y" || $answer == "Y" ]]; then
        break
    elif [[ $answer == "n" || $answer == "N" ]]; then
        installcleanup
    fi
done

# Copy installer
mkdir -p /mnt/opt/Archinstaller
cp -r "$SCRIPT_DIR"/* /mnt/opt/Archinstaller/
chmod +x /mnt/opt/Archinstaller/scripts/*

# Store UUID for encrypted EFI
if [[ $disk_encrypt == "y" && $platform == "EFI" ]]; then
    LUKS_UUID=$(blkid -s UUID -o value "$partition2")
    echo "LUKS_UUID=$LUKS_UUID" >> /mnt/opt/Archinstaller/scripts/vars.sh
fi

echo -ne "
-------------------------------------------------------------------------
                    Updating the system clock
-------------------------------------------------------------------------
"
timedatectl set-ntp true
timedatectl

clear

echo -ne "
-------------------------------------------------------------------------
                          Selecting the mirrors
-------------------------------------------------------------------------
"
echo "Updating mirrors with reflector..."
if ! reflector --verbose --latest 10 --protocol https --sort rate --save /etc/pacman.d/mirrorlist; then
    echo "Warning: Reflector failed, using existing mirrors"
    echo "You may want to manually update /etc/pacman.d/mirrorlist later"
fi

clear

echo -ne "
-------------------------------------------------------------------------
                    Installing essential packages
-------------------------------------------------------------------------
"

# Ucode
cpu_type=$(lscpu)
ucodepackage=""
if grep -E "GenuineIntel" <<< ${cpu_type}; then
    echo "Installing Intel microcode"
    ucodepackage="intel-ucode"
    #proc_ucode=intel-ucode.img
elif grep -E "AuthenticAMD" <<< ${cpu_type}; then
    echo "Installing AMD microcode"
    ucodepackage="amd-ucode"
    #proc_ucode=amd-ucode.img
else
    echo "No recognized CPU vendor - skipping microcode"
fi

# See if cryptsetuppackage is needed
encryption_package= ""
if [[ $disk_encrypt == "y" && $platform == "EFI" ]]; then
    encryption_package= "cryptsetup"
fi

packages="base sudo linux-firmware linux-lts lvm2 networkmanager openssh vim $ucodepackage $encryption_package"

# Add EFI boot manager if needed
if [[ $platform == "EFI" ]]; then
    packages+=" efibootmgr"
fi

if [[ $platform == "BIOS" ]]; then
    packages+=" grub"
fi


while true; do
    if ! pacstrap -K /mnt --noconfirm --needed ${packages}; then
        echo "ERROR: Package installation failed"
        echo "Try again.."
    else
        echo "Success"
        break
    fi
done

clear

echo -ne "
-------------------------------------------------------------------------
                      Configuring the system
-------------------------------------------------------------------------
"

genfstab -U /mnt >> /mnt/etc/fstab

if [[ $platform == "EFI" ]]; then
    echo "Fixing EFI mount boot options in fstab..."
    sed -i '/\/efi/ s/fmask=[0-9]\{4\}/fmask=0137/; s/dmask=[0-9]\{4\}/dmask=0027/' /mnt/etc/fstab

#elif [[ $platform == "BIOS" ]]; then
#    echo "Fixing BIOS mount boot options in fstab..."
#    sed -i '/\/boot/ s/fmask=[0-9]\{4\}/fmask=0137/; s/dmask=[0-9]\{4\}/dmask=0027/' /mnt/etc/fstab
